version: "3"

services:
  frontend:
    container_name: frontend
    build: client
    restart: always
    volumes:
      - ./client:/app/
    depends_on:
      - fastapi
    ports:
      - "8004:8004"
    networks:
      net:
        ipv4_address: 192.168.220.2

  fastapi:
    container_name: fastapi
    restart: always
    volumes:
      - ./api:/api/
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      net:
        ipv4_address: 192.168.220.3

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "123"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - ./db:/var/lib/postgresql
    ports:
      - "54324:5432"
    networks:
      net:
        ipv4_address: 192.168.220.4

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.220.0/24
